### ISSUE TITLE
PID tuning stuck screen

### ISSUE THREAD

**Issue by patriko123** [kisslorand/BTT-TFT-FW#1]
Hello when I do PID autotune I remain stuck in screen Busy processing please wait. After dome time is on screen pid tuning complete but i remain stuck and then after some Timeout reached! Busy processing please wait. Should this work like that ?

**Comment by kisslorand** [comment]
Please provide more details. For what did you do the PID tuning?

**Comment by patriko123** [comment]
For hotend and bed

**Comment by kisslorand** [comment]
I just tested PID autotune and cannot reproduce the mentioned issue.
Try, if you can, to see if you have the same issue when starting PID tune from terminal or any other guest connected to the motherboard (Octoprint, Pronterface, etc). If yes you should look at your motherboard configs.

**Comment by kisslorand** [comment]
Closing it due to inactivity.
