### ISSUE TITLE
Print Completes but TFT doesn't switch "Stop" button to "back" button and timer continues to run.

### ISSUE THREAD

**Issue by buryboi** [kisslorand/BTT-TFT-FW#10]
On TFT28 4.0.27.bin Came from digant's TFT.  I have to manually Stop the print which "cancels" it.  Do I need a certain gcode at the end of prints?

**Comment by kisslorand** [comment]
Check your gcode file please. Is the last line an empty line? If not, than add an empty line to the end of the gcode file.

**Comment by buryboi** [comment]
[Cube_PETG_42s.zip](https://github.com/kisslorand/BTT-TFT-FW/files/13698037/Cube_PETG_42s.zip)

It appears to have 3 empty lines at the end. (Attached as a zip).  Thanks, I reflashed Digant and confirmed the print completes as expected.

**Comment by kisslorand** [comment]
> It appears to have 3 empty lines at the end.

Make it only one.

**Comment by buryboi** [comment]
That seems to have solved it!  Is there a slicer script to cut the extra "returns" from the end of the g-code? (I have been running Orca Slicer recently).  thank you!

**Comment by kisslorand** [comment]
> Is there a slicer script to cut the extra "returns" from the end of the g-code?

Not that I know of.
I will fix it in the TFT FW.

**Comment by kisslorand** [comment]
The issue has been fixed.
