### ISSUE TITLE
Why does config require M75 and M77 for filament runout even with PRINTJOB_TIMER_AUTOSTART enabled?

### ISSUE THREAD

**Issue by buryboi** [kisslorand/BTT-TFT-FW#11]
Config states M75 is required at GCODE start and M77 required at GCODE end in order for Filament runout sensor to work.  This works fine for me, but feels redundant with timer autostart enabled.  Does the tft not recognize the timer autostart from marlin and thus needs discrete M75?  Technically this is more of a question than an issue.  Thank you for your firmware!

**Comment by kisslorand** [comment]
It's Marlin who needs the `M75`, not the TFT. Without the initial M75 Marlin will not report the filament runout trigger.

**Comment by kisslorand** [comment]
Closing due to OP being answered.
