### ISSUE TITLE
MKS TFT28 Issue with Fonts

### ISSUE THREAD

**Issue by SpankyDevil** [kisslorand/BTT-TFT-FW#14]
MKS TFT28
Firmware MKS_TFT28_V3.0.27.x.bin
config.ini (Only changed Serial Port 1 baudrate to 250000)
TFT28 THEME_Unified Menu Material theme

When updating Fonts SD:/TFT28/font/word_unicode.fon gets to 25% and then changes to unreadable characters.
Once the update is complete the Dashboard is unreadable.

![20240509_141036](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/41b28310-cd9d-485b-b1e2-c7181ec73fec)
![20240509_141123](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/4e9b58ee-0989-4879-bd3c-7a3b506fe77e)
![20240509_141129](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/dc876d5f-4019-4cc7-b148-5f4da8d17988)
![20240509_140945](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/7e0783aa-1c15-42fa-b2f9-b1c4b82e9709)
![20240509_141007](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/57785ad4-8a87-40ac-b7a5-3a9d93cfff9f)
![20240509_141013](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/f0ab91f4-69d5-4bbb-9f3a-82eaeb846fa2)

**Comment by kisslorand** [comment]
Please try this:

- create an empty "reset.txt" file on your SD Card
- put the SD Card into the TFT's SD Card slot
- start/reboot the TFT
- restart the firmware update procedure including the addons but do not include any language file ("language_xx.ini") this time 

Let me know of the outcome of the above.

**Comment by SpankyDevil** [comment]
1. Did a full format on an 8GB SD Card.
2. Created reset.txt
3. put the SD Card into the TFT's SD Card slot
4. start/reboot the TFT
5. Completed Touch Calibration
![20240514_184953](https://github.com/kisslorand/BTT-TFT-FW/assets/75092373/66eec445-da65-4e22-9ca1-72870a27e4e5)

6. Deleted reset.DONE
7.Placed the following files on the SD Card
**Firmware MKS_TFT28_V3.0.27.x.bin** - renamed to MKSTFT28.bin
**config.ini** (Only changed Serial Port 1 baudrate to 250000)
**TFT28** - folder from THEME_Unified Menu Material theme

Results still not in English.

Here is the About screen and the change language screen.
![20240514_185629](https://github.com/kisslorand/BTT-TFT-FW/assets/75092373/9b2cde20-9c4d-474a-9102-b1e274f80d76)
![20240514_185647](https://github.com/kisslorand/BTT-TFT-FW/assets/75092373/14da9bf1-cdb8-466d-80d4-91f32bdca6f6)

**Comment by kisslorand** [comment]
Can you please post a picture of the back  of your TFT board (where the MCU is)?

**Comment by SpankyDevil** [comment]
![20240515_173210](https://github.com/kisslorand/BTT-TFT-FW/assets/75092373/1cb63fd6-56de-4fb4-82f8-8e1720bc87f7)

**Comment by kisslorand** [comment]
It seems you have a V2 TFT board which is not compatible with this firmware.

**Comment by kisslorand** [comment]
It's kind of hard to do it without having the TFT.

I recommend to buy a compatible TFT, it should be really cheap nowadays.

**Comment by SpankyDevil** [comment]
Fully understand.
I am happy to work with you and accept any risk of bricking the device if this is an option?
I feel this shouldn't need too many changes since it is working just an issue with the language or fonts.

I don't know if it makes any difference but the Original MKS TFT28_32_v3.0.6 firmware works correctly but doesn't have all the cool features of this firmware.

I am a Senior System Engineer so have lots of experience with flashing firmware, Serial connections, and some programming knowledge but not to this level required.

I find it strange that it is all in English until it gets to 25% flashing "word_unicode.fon" then it changes to something that looks like Chinese but I do not think it is Chinese.

**Comment by SpankyDevil** [comment]
I deleted the word_unicode.fon file from within the TFT28\Font\ Folder and created a blank file with the same name.
Reflashed and now everything is working in English.

![20240517_092738](https://github.com/kisslorand/BTT-TFT-FW/assets/75092373/58d6a600-d7ac-4b77-b352-7d21e9e27ece)
![20240517_092809](https://github.com/kisslorand/BTT-TFT-FW/assets/75092373/87d96aa8-784b-4a72-8293-6cbb9b9307ab)
![20240517_092921](https://github.com/kisslorand/BTT-TFT-FW/assets/75092373/91552b2f-4cec-4e29-a1f2-b790459f464c)

**Comment by kisslorand** [comment]
Just as I thought, memory corruption/limitation is the culprit of your issues.
As you can see 193.65% SPIFlash is used. This FW's addons just doesn't fit into the memory of your TFT. You have only 4MB of SPI flash, 8MB is needed.

**Comment by SpankyDevil** [comment]
How is that even possible to store nearly 8gb on a 4gb.
Im surprised its running so well.

I guess thats the difference between the MKS TFT28 V2.0 and V3.0 4gb vs 8gb

**Comment by kisslorand** [comment]
> How is that even possible to store nearly 8gb on a 4gb.

It's not possible.

> Im surprised its running so well.

Me too.

> I guess that's the difference between the MKS TFT28 V2.0 and V3.0 4gb vs 8gb

Could be, among other stuff.
