### ISSUE TITLE
Support for MKS HLK-WIFI module on MKS TFT28

### ISSUE THREAD

**Issue by SpankyDevil** [kisslorand/BTT-TFT-FW#15]
The original MKS TFT28 supports wifi using the MKS HLK-WIFI module.
Is this supported with your firmware?

**Comment by kisslorand** [comment]
The original MKS TFT28 firmware uses different communication protocol for WiFi modules than this firmware so it is most probably not compatible with the module you mentioned.

**Comment by SpankyDevil** [comment]
In the config file is this "P2: WIFI    (e.g. ESP3D)" referring to Wifi Adaptor connected to the TFT or the main board eg Ramps?

**Comment by kisslorand** [comment]
It's referring to a WiFi module connected to the TFT.

**Comment by SpankyDevil** [comment]
What is the preferred method for WiFi, connecting to the TFT or the Mainboard?

**Comment by kisslorand** [comment]
I would say mainboard if possible.
