### ISSUE TITLE
Artillery sidewinder X2

### ISSUE THREAD

**Issue by April-ha** [kisslorand/BTT-TFT-FW#2]
Hello,
I have a sidewinder x2 with TFT STM32F107VCT6 supplied with the printer.
When I boot the printer, V3.0.0 appears. Should I use MKS_TFT28_V3.0.27.x.bin ?
What is the difference with MKS_TFT28_V4.0.27.x.bin it is better ?
if I want to compile I can use the BIGTREETECH sources or your forked ?, Are your sources more up to date ?
Thank you for your work.

**Comment by kisslorand** [comment]
MKS_TFT28_V4.0.27.x.bin is the only FW suitable for your printer's TFT. 

Sent from Yahoo Mail on Android 
 
  On Sat, Aug 26, 2023 at 6:18, ***@***.***> wrote:   


Hello,
I have a sidewinder x2 with TFT STM32F107VCT6 supplied with the printer.
When I boot the printer, V3.0.0 appears. Should I use MKS_TFT28_V3.0.27.x.bin ?
What is the difference with MKS_TFT28_V4.0.27.x.binit is better ?
Thank you for your work.

**Comment by April-ha** [comment]
Thanks, I'll give it a try
