### ISSUE TITLE
patched bootloader needed for TFT update?

### ISSUE THREAD

**Issue by bagges** [kisslorand/BTT-TFT-FW#3]
Is the patched bootloader (chirp or patched) needed to update the firmware of the TFT (GD32F305)? Is it still possible to restore the factory bootloader / tft firmware afterwards?

I'd like to have the chirp version with the latest TFT FW running on my sidewinder x2.

Thanks.

**Comment by kisslorand** [comment]
FW can be updated with original bootloader also so no need for a patched bootloader. Original bootloader can be restored.

**Comment by bagges** [comment]
thank you!
