### ISSUE TITLE
Thumbnails disappearing when going through files.

### ISSUE THREAD

**Issue by discip** [kisslorand/BTT-TFT-FW#7]
As I'm using thumbnails I noticed that they disappear if you go to the next page and only come back after the drive was excited and re-entered.

**Comment by kisslorand** [comment]
It's something I have to check on the original firmware. Will come back with the results, I am sure it can be solved.

**Comment by discip** [comment]
I remember having a similar issue with the original firmware.

If I found the right spot than this should be the fix:

https://github.com/digant73/BIGTREETECH-TouchScreenFirmware/commit/82d754bee8fc524d3b4db8579fd540b6b410ede7

**Comment by kisslorand** [comment]
The link you gave me is about the file extension, not about thumbnails.

**Comment by discip** [comment]
Yes, but it is somehow related to this issue as discussed here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2300#issuecomment-1003675156

**Comment by kisslorand** [comment]
OK. I will look into it.

**Comment by kisslorand** [comment]
The issue has been found, working on a fix for it.

**Comment by kisslorand** [comment]
It has been fixed, repository is updated with the fixes. Thank you!

**Comment by discip** [comment]
## Clearly I'm the one having to thank you! 😃👍

Will test as soon as I'm home again.

**Comment by discip** [comment]
## Unfortunately there was a print running up until now, which on the other hand proved the hesitation problem to be solved! 👍🏻 🎉

# After flashing the latest firmware the previously described ISSUES are GONE!
# Thank you so much!

**Comment by discip** [comment]
May I ask if it makes sense to improve this browsing behavior even further without affecting performance?

I was thinking about storing the _'**thumbnails-pages**'_ after loading so that they don't have to be loaded individually each time the files are browsed.

**Comment by kisslorand** [comment]
There is no place to store them, they are loaded directly into the RAM of the display driver as the file is accessed.

**Comment by discip** [comment]
Alright.
Thanks for the clarification! 👍
