### ISSUE TITLE
config.ini not compatible with TFT43

### ISSUE THREAD

**Issue by discip** [kisslorand/BTT-TFT-FW#8]
I tried both:

previous version 
**`"Machine Size / Build Area"`**

as well as

latest version
**`"Motion limits"` and `"Bed size"`**

Both resulting in:

    Invalid Keyword:

    size_min: ...

and

    Invalid Keyword:

    size_max: ...

And one additional little issue related to TFT43 (maybe others too but definitely **NOT MKS28**):

The text on the info-screen about the System, Machine, Board ... is shifted down so that the lowest lines are not legible. 😅

**Comment by kisslorand** [comment]
There should be no such keyword as "size_min" and "size_max" in the "config.ini". I updated "config.ini", please check it out.

**Comment by discip** [comment]
> There should be no such keyword as "size_min" and "size_max"

My bad I missed exactly that part. 😅
Its working now! 👍🏻


> I will look into it.

Thanks in advance!

**Comment by kisslorand** [comment]
> The text on the info-screen about the System, Machine, Board ... is shifted down so that the lowest lines are not legible. 😅

Issue has been found and fixed for the next release.

**Comment by discip** [comment]
## Great! 👍🏻 Your responsiveness and care are highly commendable!

**Comment by kisslorand** [comment]
The repository is updated with the fixes.

**Comment by discip** [comment]
I'm speechless!
Wow!

Will test as soon as I get home.
